name: PigeonChickenDupe
version: '1.1'
main: top.mcocet.pigeonChickenDupe.PigeonChickenDupe
api-version: '1.21'
folia-supported: true
authors: [ MCOCET ]
description: 通过鸡和带有仓库的生物，复制玩家的物品
website: https://home.mcocet.top
